# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'reactChatApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for reactChatApp
  pod 'Firebase/Messaging'
  target 'reactChatApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'reactChatAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'reactChatApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for reactChatApp-tvOS

 # target 'reactChatApp-tvOSTests' do
  #  inherit! :search_paths
    # Pods for testing
  # end

end
